
--today
select VALUE_DATE as "DATE", RESULT_NUM3/1000000 as "VALUE/1000000" 
from
DQ_DETAILJOURNAL_TRAN_DWMON
WHERE (VALUE_DATE, XK) IN
(
 select VALUE_DATE, max(XK) 
 from DQ_DETAILJOURNAL_TRAN_DWMON 
 where DQ_CONTROL_UK=98
 group by VALUE_DATE
)
order by VALUE_DATE asc;


--history
select VALUE_DATE as "DATE", max(RESULT_NUM3)/1000000000  as "maxVALUE/1000000000"  
from 
DQ_DETAILJOURNAL_TRAN_DWMON
where DQ_CONTROL_UK= 98
group by VALUE_DATE;

