
SELECT * FROM DQ_PARAMS_NEWDQ
order by START_TIME;


select max(START_TIME)
from DQ_PARAMS_NEWDQ
where CTL_WORKFLOW_NAME in ('WF_CTL_DMFR_LOADING_AW_INCR', 'WF_CTL_DMFR_LOADING_FULL')
order by CTL_WORKFLOW_NAME;


SELECT * FROM DQ_HEADINGS_NEWDQ
WHERE LIST_ID in (258, 263, 269, 272, 273);


SELECT * FROM DQ_LIST_NEWDQ WHERE LIST_ID in (258, 263, 269, 272, 273);    


SELECT * FROM DQ_LIST_NEWDQ WHERE LIST_ID in (258, 263, 269, 272, 273, 282, 570);        


select *
from REP_DQMON_PROD.OPB_TASK_INST_RUN@DWH_INFA_PROD
where TASK_NAME in ('s_m_DQ_SQL_RUN_N115') 
order by END_TIME desc;
